apiVersion: v1
kind: PersistentVolume
metadata:
  name: quorum-bootnode-persistence 
  labels:
    type: local
spec:
  storageClassName: bootnode
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/qdata/qdata_0"
