apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootnode-deploy
  labels:
    app: quorum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quorum
  template:
    metadata:
        labels:
          app: quorum
    spec:
      volumes:
      - name: quorum-storage
        persistentVolumeClaim:
          claimName: quorum-bootnode-pv-claim
      containers:
        - name: quorum
          volumeMounts:
          - mountPath: "/qdata"
            name: quorum-storage
          command:
            - /bin/sh
            - -c
            - bootnode -nodekey /qdata/nodekey
          image: ssmay0/quorum:latest
          livenessProbe:
            httpGet:
              path: /
              port: 8545
          readinessProbe:
            httpGet:
              path: /
              port: 8545
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 128Mi
