{{- range $k, $v := .Values.quorumClusterNodes }}
apiVersion: v1
kind: Service
metadata:
  name: "quorum-{{ $v.name }}-svc"
spec:
  selector:
    app: "quorum-{{ $v.name }}"
  ports:
    - protocol: TCP
      name: quorum
      port: 30303
      targetPort: 30303
    - name: http
      port: 8545
      targetPort: 8545
---
{{- end }}
