apiVersion: v1
kind: Service
metadata:
  name: bootnode-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: bootnode
  ports:
    - protocol: TCP
      port: 30301
      targetPort: 30301