apiVersion: apps/v1
kind: Deployment
metadata:
  name: racecourse-deploy
  labels:
    app: racecourse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: racecourse
  template:
    metadata:
        labels:
          app: racecourse
    spec:
      containers:
        - name: racecourse
          command:
            - /bin/sh
            - -c
            - npm start
          image: ssmay0/racecourse:latest
          resources:
            limits:
              cpu: 512m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: racecourse-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: racecourse
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000